Partitions
memphisdev/memphis.py pull request #196
Opened 2023-08-08 21:11 UTC by daniel-davidd

2023-08-08 22:50 UTC, rnowling-memphis requested changes
Please fix any associated Pylint issues.

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/memphis.py
> +            if not creation_res["partitions_update"]["partitions_list"] is None:
please move the "not" before the "None":

`if creation_res["partitions_update"]["partitions_list"] is not None:`

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/partition_generator.py
> +        return partition_to_return
Missing end of file marker

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/partition_generator.py
> +
Remove blank lines at top

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/partition_generator.py
> +    def next(self):
If you rename this to `__next__`, you can then use the more Pythonic approach of working with iterators: `next(iter)`

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/partition_generator.py
> +class PartitionGenerator:
Can you add some documentation indicating what this class does and how it should be used?

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/producer.py
> +            if not self.internal_station_name in self.connection.partition_producers_updates_data:
Change to `if self.internal_station_name not in self.connection.partition_producers_updates_data`

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/memphis.py
> +            if not create_res["partitions_update"]["partitions_list"] is None:
Please change to `if create_res["partitions_update"]["partitions_list"] is not None`

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/consumer.py
> +        if not self.inner_station_name in self.connection.partition_consumers_updates_data:
Please change to `if self.inner_station_name not in self.connection.partition_consumers_updates_data`

2023-08-08 22:50 UTC, rnowling-memphis commented on memphis/consumer.py
> +                if not self.inner_station_name in self.connection.partition_consumers_updates_data:
Please change to `if self.inner_station_name not in self.connection.partition_consumers_updates_data`

2023-08-09 10:03 UTC, idanasulinmemphis approved these changes

2023-08-09 10:04 UTC, merged